# Generated by Django 5.2.7 on 2025-11-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userinfo_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='register_time',
            field=models.CharField(default='2025-11-05 21:52:32', max_length=20, verbose_name='创建时间'),
        ),
    ]
