# Generated by Django 5.2.7 on 2025-11-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userinfo_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
