# Generated by Django 5.2.7 on 2025-11-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_userinfo_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar_name',
            field=models.CharField(blank=True, help_text='用户头像的文件名', max_length=150, null=True, verbose_name='头像名称'),
        ),
    ]
