# Generated by Django 5.2.7 on 2025-11-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_alter_userinfo_register_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False, verbose_name='投票ID')),
                ('question', models.CharField(max_length=50, verbose_name='问题')),
                ('question_description', models.CharField(blank=True, max_length=200, verbose_name='问题描述')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to='login.userinfo', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '投票',
                'verbose_name_plural': '投票',
                'db_table': 'tb_polls',
            },
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=50, verbose_name='选项文本')),
                ('votes', models.IntegerField(default=0, verbose_name='票数')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.poll', verbose_name='投票')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
                'db_table': 'tb_choices',
            },
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='polls.choice', verbose_name='选项')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='polls.poll', verbose_name='投票')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='login.userinfo', verbose_name='投票人')),
            ],
            options={
                'verbose_name': '投票记录',
                'verbose_name_plural': '投票记录',
                'db_table': 'tb_votes',
                'unique_together': {('poll', 'voter')},
            },
        ),
    ]
